FROM node:lts

WORKDIR /app

# Copy only package files first
COPY package*.json ./

# Install dependencies with memory limit
RUN node --max-old-space-size=2048 $(which npm) install --legacy-peer-deps

# Copy the rest of the app
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]